// internal/adapters/__rest/webpanel/src/routes/login/+page.svelte
<script lang="ts">
	let username: string = '';
	let password: string = '';
	let error: string = '';

	const handleLogin = async (event: Event) => {
		event.preventDefault();

		try {
			// Отправка POST-запроса на сервер
			const response = await fetch('/api/login', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({ username, password })
			});

			// if (!response.ok) {
			// 	// Обработка ошибок, если запрос не удался
			// 	throw new Error(response.status + ' ' + response.statusText);
			// }

			const data = await response.json();

			if (data.authToken) {
				// Сохранение authToken в куки
				document.cookie = `authToken=${data.authToken}; path=/;`;

				// Перенаправление на главную страницу
				window.location.href = '/';
			} else {
				error = data.message;
			}
		} catch (err: unknown) {
			if (err instanceof Error) {
				error = err.message;
			} else {
				error = 'Неизвестная ошибка';
			}
		}
	};
</script>

<main class="flex items-center justify-center h-screen font-mono">
	<div class="bg-white border-2 border-gray-300 rounded-lg p-4 w-full max-w-sm">
		<h2 class="text-2xl font-bold mb-2 text-center">МОЛОКОД</h2>
		<h2 class="text-1xl mb-2 text-center">Авторизация</h2>

		<form on:submit={handleLogin}>
			<div class="mb-4">
				<label class="block text-sm font-bold mb-2" for="username">Логин</label>
				<input
					id="username"
					bind:value={username}
					type="text"
					class="appearance-none border-2 border-gray-300 rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline"
					placeholder="Введите логин"
				/>
			</div>

			<div class="mb-6">
				<label class="block text-sm font-bold mb-2" for="password">Пароль</label>
				<input
					id="password"
					bind:value={password}
					class="appearance-none border-2 border-gray-300 rounded w-full py-2 px-3 mb-2 leading-tight focus:outline-none focus:shadow-outline"
					type="password"
					placeholder="Введите пароль"
				/>
			</div>

			<button
				class="bg-white hover:bg-gray-200 px-3 rounded border-solid border-2 border-gray-500"
				type="submit"
				>Войти
			</button>
			{#if error}
				<span class="p-2 text-red-500">{error}</span>
			{/if}
		</form>
	</div>
</main>

// internal/api/http_web/webpanel/src/pages/login.jsx
// Форма для авторизации

export default function Login() {
    return (
        <>
            <div className="bg-gray-100 flex items-center justify-center h-screen">
                <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-sm">
                    <h2 className="text-2xl font-bold mb-2 text-center">МОЛОКОД</h2>
                    <h2 className="text-1xl mb-2 text-center">Авторизация</h2>
                    <form>
                        <div className="mb-4">
                            <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="username">
                                Логин
                            </label>
                            <input
                                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                id="username" type="text" placeholder="Введите логин"></input>
                        </div>
                        <div className="mb-6">
                            <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="password">
                                Пароль
                            </label>
                            <input
                                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-2 leading-tight focus:outline-none focus:shadow-outline"
                                id="password" type="password" placeholder="Введите пароль"></input>
                        </div>
                        <div className="flex items-center justify-between">
                            <button
                                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                                type="button">
                                Войти
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </>
    )
}
