// internal/api/http_web/webpanel/src/components/LeftMenu.jsx
import React from "react";
import { Link } from "gatsby";

export default function LeftMenu() {
    return (
        <nav className="bg-white w-48 border-r border-gray-500">
            <ul>
                <li>
                    <Link to="c1" className="hover:bg-gray-200 block py-2 px-4">
                        Главная
                    </Link>
                </li>
                <li>
                    <Link to="t2" className="hover:bg-gray-200 block py-2 px-4">
                        О нас
                    </Link>
                </li>
                <li >
                    <Link to="#" className="hover:bg-gray-200 block py-2 px-4">
                        Блог
                    </Link>
                </li>
                <li >
                    <Link to="login" className="hover:bg-gray-200 block py-2 px-4">
                        Логин
                    </Link>
                </li>
            </ul>
        </nav>
    )
}

// internal/api/http_web/webpanel/src/components/LeftMenu.svelte
<script lang="ts">
	export let currentPath: string = '';

	const isActive = (path: string) => currentPath === path;
</script>

<nav class="bg-white w-48 border-r border-gray-500">
	<ul>
		<li>
			<a href="/" class={`hover:bg-gray-200 block py-2 px-4 ${isActive('/') ? 'bg-gray-300' : ''}`}>
				Главная
			</a>
		</li>
		<li>
			<a href="/" class={`hover:bg-gray-200 block py-2 px-4 ${isActive('/') ? 'bg-gray-300' : ''}`}>
				О нас
			</a>
		</li>
		<li>
			<a
				href="/login"
				class={`hover:bg-gray-200 block py-2 px-4 ${isActive('/login') ? 'bg-gray-300' : ''}`}
			>
				Логин
			</a>
		</li>
	</ul>
</nav>
